const SHOP_DATA = [
  {
    id: 1,
    title: "Canned foods",
    routeName: "canned",
    items: [
      {
        id: 1,
        name: "Green Bamieh Durra 850g",
        imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        price: 7,
      },
      {
        id: 2,
        name: "Foul Lebanaise Durra",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 1,
      },
      {
        id: 3,
        name: "Foul Shamiya Durra",
        imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
        price: 1,
      },
      {
        id: 4,
        name: "Hommus Durra",
        imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
        price: 2,
      },
      {
        id: 5,
        name: "Foul Medammes Durra",
        imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
        price: 0.8,
      },
      {
        id: 6,
        name: "Grape Leaves Durra",
        imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
        price: 6,
      },
      {
        id: 7,
        name: "Corn Beef Hana",
        imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
        price: 4.5,
      },
      {
        id: 8,
        name: "Mortadella Hana Chicken 200g",
        imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
        price: 2.5,
      },
      {
        id: 9,
        name: "Hommus Alkasih 4X135g",
        imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
        price: 6,
      },
      {
        id: 10,
        name: "Tahini Durra",
        imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
        price: 7,
      },
    ],
  },
  {
    id: 2,
    title: "Beverages & Liquids",
    routeName: "beverages",
    items: [
      {
        id: 1,
        name: "English Tea Ahmad",
        imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
        price: 6.5,
      },
      {
        id: 2,
        name: "Green Tea Ahmad",
        imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
        price: 6,
      },
      {
        id: 3,
        name: "Haseeb Coffe Black",
        imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
        price: 7.5,
      },
      {
        id: 4,
        name: "Haseeb Coffe Extra",
        imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
        price: 8,
      },
      {
        id: 5,
        name: "Haseeb Coffe Gold",
        imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
        price: 8,
      },
      {
        id: 6,
        name: "Kharta Mate",
        imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
        price: 5,
      },
      {
        id: 7,
        name: "Lipton Tea 25 bag",
        imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
        price: 1.5,
      },
      {
        id: 8,
        name: "Lipton Tea 100 bag",
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        price: 3.5,
      },
      {
        id: 9,
        name: "Milk Powder Nido 2.5 KG",
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        price: 14,
      },
      {
        id: 10,
        name: "Milk Powder Nido 400G",
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        price: 4.5,
      },
    ],
  },
  {
    id: 3,
    title: "Dairy & Cheese",
    routeName: "dairy",
    items: [
      {
        id: 1,
        name: "Akkawi Cheese Alraii",
        imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
        price: 12,
      },
      {
        id: 2,
        name: "Baladia Labaneh Balls",
        imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
        price: 7,
      },
      {
        id: 3,
        name: "Gazi White Cheese 55% ",
        imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
        price: 10,
      },
      {
        id: 4,
        name: "Gazi White Cheese 60%",
        imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
        price: 12,
      },
      {
        id: 5,
        name: "Gazi White Cheese 65%",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 13,
      },
      {
        id: 6,
        name: "Gazi Yellow Cheese 400g",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 7.5,
      },
      {
        id: 7,
        name: "Nabulsi Cheese Baladi",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 11,
      },
      {
        id: 8,
        name: "Nabulsi Cheese Alraii",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 12,
      },
      {
        id: 9,
        name: "Puck cream Cheese 240g",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 2.5,
      },
      {
        id: 10,
        name: "Puck cream Cheese 910g",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 6,
      },
    ],
  },
  {
    id: 4,
    title: "Dessert & Chips",
    routeName: "dessert",
    items: [
      {
        id: 1,
        name: "Durra Bread Sticks",
        imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
        price: 5,
      },
      {
        id: 2,
        name: "Durra Halawa 350g",
        imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
        price: 3.5,
      },
      {
        id: 3,
        name: "Durra Halawa 700g",
        imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
        price: 6,
      },
      {
        id: 4,
        name: "Muhtar Ballurieh 900g ",
        imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
        price: 22,
      },
      {
        id: 5,
        name: "Muhtar Barazek",
        imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
        price: 12,
      },
      {
        id: 6,
        name: "Muhtar Maamoul Date",
        imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
        price: 13,
      },
      {
        id: 7,
        name: "Muhtar Maamoul Nuts",
        imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
        price: 18,
      },
      {
        id: 8,
        name: "Muhtar Mix Arabic 500g",
        imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
        price: 20,
      },
      {
        id: 9,
        name: "Muhtar Mix Arabic 750g",
        imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
        price: 27,
      },
      {
        id: 10,
        name: "Muhtar Nawashef",
        imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
        price: 14,
      },
    ],
  },
  {
    id: 5,
    title: "Rice & Grain",
    routeName: "mens",
    items: [
      {
        id: 1,
        name: "Alshaalan Basmati Rice 2KG",
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        price: 5,
      },
      {
        id: 2,
        name: "Alshaalan Basmati Rice 10KG",
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        price: 18,
      },
      {
        id: 3,
        name: "Bulgur Hard Baladna",
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        price: 3.5,
      },
      {
        id: 4,
        name: "Bulgur Soft",
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        price: 3,
      },
      {
        id: 5,
        name: "Falafel Baladna",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 4.5,
      },
      {
        id: 6,
        name: "Freekeh Baladna",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 5,
      },
      {
        id: 7,
        name: "Sun White Rice 2KG",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 4,
      },
      {
        id: 8,
        name: "Red Beans Suntat",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 2.5,
      },
      {
        id: 9,
        name: "White Beans Altunsa",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 3,
      },
      {
        id: 10,
        name: "White Beans Baladna",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 3.5,
      },
    ],
  },
  {
    id: 6,
    title: "NonFood",
    routeName: "nonfood",
    items: [
      {
        id: 1,
        name: "Coffe Pot",
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        price: 5,
      },
      {
        id: 2,
        name: "Dettol 1L",
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        price: 6,
      },
      {
        id: 3,
        name: "Elegance Hair GEl Blue",
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        price: 7,
      },
      {
        id: 4,
        name: "Elegance Hair GEl Green",
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        price: 7,
      },
      {
        id: 5,
        name: "Al Emlaq Limon",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 4.5,
      },
      {
        id: 6,
        name: "Al Emlaq Rose",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 4.5,
      },
      {
        id: 7,
        name: "MIM Hair Removal",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 2,
      },
      {
        id: 8,
        name: "Sabeq",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 5,
      },
      {
        id: 9,
        name: "Straw Mate",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 3,
      },
      {
        id: 10,
        name: "Tea Jug",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 8,
      },
    ],
  },
  {
    id: 7,
    title: "Oils & Ghee",
    routeName: "mens",
    items: [
      {
        id: 1,
        name: "Aseel Ghee 1KG",
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        price: 9,
      },
      {
        id: 2,
        name: "Olive Oil Baladna 1L",
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        price: 5,
      },
      {
        id: 3,
        name: "Sun Oil Baladna 2L",
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        price: 4.5,
      },
      {
        id: 4,
        name: "Olive Oil Durra 2L",
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        price: 10,
      },
      {
        id: 5,
        name: "Sun Oil Durra 3L",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 7,
      },
      {
        id: 6,
        name: "Golden Medal Ghee 400G",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 5.5,
      },
      {
        id: 7,
        name: "Golden Medal Ghee 800G",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 10,
      },
      {
        id: 8,
        name: "Khanum Ghee 500G",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 5,
      },
      {
        id: 9,
        name: "Mazola Corn Oil 2L",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 6,
      },
      {
        id: 10,
        name: "Zarzour Olive Oil 750ML",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 3.5,
      },
    ],
  },
  {
    id: 8,
    title: "Bread & Pastries",
    routeName: "pastries",
    items: [
      {
        id: 1,
        name: "Angel Hair Durra",
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        price: 2.5,
      },
      {
        id: 2,
        name: "Italian Macaroni Durra",
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        price: 3,
      },
      {
        id: 3,
        name: "Lasagne Durra",
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        price: 3.5,
      },
      {
        id: 4,
        name: "Farine BIO T55",
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        price: 1.5,
      },
      {
        id: 5,
        name: "Indomie Chicken",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 1,
      },
      {
        id: 6,
        name: "Indomie Special",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 1,
      },
      {
        id: 7,
        name: "Indomie Vegetabl",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 1,
      },
      {
        id: 8,
        name: "Spaggiti Durra",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 1.5,
      },
      {
        id: 9,
        name: "Syrian Bread 700G",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 0.5,
      },
      {
        id: 10,
        name: "Wheat Flour 1KG",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 1,
      },
    ],
  },
  {
    id: 9,
    title: "Spices & Nuts",
    routeName: "spices",
    items: [
      {
        id: 1,
        name: "Baladna Coconut",
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        price: 2,
      },
      {
        id: 2,
        name: "Baladna Kebeh spices",
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        price: 2.5,
      },
      {
        id: 3,
        name: "Baladna Red Zaatar",
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        price: 4.5,
      },
      {
        id: 4,
        name: "Baladna Curry spices",
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        price: 2,
      },
      {
        id: 5,
        name: "Durra chicken spices",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 1.5,
      },
      {
        id: 6,
        name: "Durra Green Zaatar",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 5,
      },
      {
        id: 7,
        name: "Durra Seven spices",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 2.5,
      },
      {
        id: 8,
        name: "Hellmann's Ketchup",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 3.5,
      },
      {
        id: 9,
        name: "Durra Mandi spices",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 2,
      },
      {
        id: 10,
        name: "Mazola Mayo",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 3.5,
      },
    ],
  },
];
